import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import http from 'node:http';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { Server } from 'socket.io';
import { createClient } from 'redis';
import { PrismaClient, RoomRole } from '@prisma/client';
import { RtcTokenBuilder, RtcRole } from 'agora-access-token';
import { z } from 'zod';
import crypto from 'node:crypto';

const prisma = new PrismaClient(); const app = express(); const httpServer = http.createServer(app); const port = Number(process.env.PORT || 4000); const secret = process.env.JWT_SECRET || 'dev-secret-change-me';
const redis = process.env.REDIS_URL ? createClient({url:process.env.REDIS_URL}) : null; redis?.on('error', e => console.error('redis',e.message)); redis?.connect().catch(e=>console.warn('Redis unavailable:',e.message));
app.use(helmet()); app.use(cors({origin:process.env.CLIENT_ORIGIN === '*' ? true : process.env.CLIENT_ORIGIN})); app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:60_000,limit:120}));
type AuthRequest = Request & { userId?: string }; const tokenFor = (id:string) => jwt.sign({sub:id},secret,{expiresIn:'15m'}); const refreshFor = (id:string) => jwt.sign({sub:id,type:'refresh'},secret,{expiresIn:'30d'});
const auth = async (req:AuthRequest,res:Response,next:NextFunction) => { try { const raw=req.headers.authorization?.replace('Bearer ',''); if(!raw) throw Error(); const payload=jwt.verify(raw,secret) as {sub:string}; req.userId=payload.sub; next(); } catch { res.status(401).json({error:'Authentication required'}); } };
const userShape = {id:true,username:true,email:true,phone:true,avatarUrl:true,bio:true,isVerified:true};
app.get('/health',(_,res)=>res.json({ok:true,service:'ms-rooms-api'}));
app.post('/auth/register',async(req,res)=>{ const parsed=z.object({identifier:z.string().min(3),username:z.string().min(3).max(24).regex(/^[a-zA-Z0-9_]+$/),password:z.string().min(8)}).safeParse(req.body); if(!parsed.success)return res.status(400).json({error:'Invalid registration data'}); const {identifier,username,password}=parsed.data; const email=identifier.includes('@')?identifier.toLowerCase():undefined; const phone=email?undefined:identifier; try { const hash=await bcrypt.hash(password,12); const user=await prisma.user.create({data:{email,phone,username,passwordHash:hash}}); return res.status(201).json({user:{...user,passwordHash:undefined},accessToken:tokenFor(user.id),refreshToken:refreshFor(user.id)}); } catch { return res.status(409).json({error:'Email, phone, or username already exists'}); } });
app.post('/auth/login',async(req,res)=>{ const parsed=z.object({identifier:z.string(),password:z.string()}).safeParse(req.body); if(!parsed.success)return res.status(400).json({error:'Invalid login data'}); const user=await prisma.user.findFirst({where:{OR:[{email:parsed.data.identifier.toLowerCase()},{phone:parsed.data.identifier},{username:parsed.data.identifier}]}}); if(!user || !(await bcrypt.compare(parsed.data.password,user.passwordHash)))return res.status(401).json({error:'Invalid credentials'}); res.json({user:{...user,passwordHash:undefined},accessToken:tokenFor(user.id),refreshToken:refreshFor(user.id)}); });
app.post('/auth/refresh',(req,res)=>{try{const p=jwt.verify(req.body.refreshToken,secret) as {sub:string,type:string};if(p.type!=='refresh')throw Error();res.json({accessToken:tokenFor(p.sub)});}catch{res.status(401).json({error:'Invalid refresh token'});}});
app.post('/auth/otp/request',async(req,res)=>{const parsed=z.object({destination:z.string().min(5)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'A valid email or phone is required'});const code=String(Math.floor(100000+Math.random()*900000));await prisma.otpCode.deleteMany({where:{destination:parsed.data.destination}});await prisma.otpCode.create({data:{destination:parsed.data.destination,codeHash:crypto.createHash('sha256').update(code+secret).digest('hex'),expiresAt:new Date(Date.now()+10*60*1000)}});console.log(`[OTP development delivery] ${parsed.data.destination}: ${code}`);res.status(202).json({message:'Verification code sent'});});
app.post('/auth/otp/verify',async(req,res)=>{const parsed=z.object({destination:z.string().min(5),code:z.string().length(6),username:z.string().min(3).max(24).regex(/^[a-zA-Z0-9_]+$/).optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid verification data'});const record=await prisma.otpCode.findFirst({where:{destination:parsed.data.destination,expiresAt:{gt:new Date()}}});const hash=crypto.createHash('sha256').update(parsed.data.code+secret).digest('hex');if(!record||record.codeHash!==hash)return res.status(401).json({error:'Invalid or expired verification code'});const email=parsed.data.destination.includes('@')?parsed.data.destination.toLowerCase():undefined;const phone=email?undefined:parsed.data.destination;let user=await prisma.user.findFirst({where:{OR:[{email},{phone}]}});if(!user){const username=parsed.data.username||`user_${crypto.randomBytes(4).toString('hex')}`;user=await prisma.user.create({data:{email,phone,username,passwordHash:await bcrypt.hash(crypto.randomBytes(24).toString('hex'),12),isVerified:true}});}else if(!user.isVerified)user=await prisma.user.update({where:{id:user.id},data:{isVerified:true}});await prisma.otpCode.delete({where:{id:record.id}});res.json({user:{...user,passwordHash:undefined},accessToken:tokenFor(user.id),refreshToken:refreshFor(user.id)});});
app.get('/users/me',auth,async(req:AuthRequest,res)=>res.json(await prisma.user.findUnique({where:{id:req.userId},select:userShape}))); app.patch('/users/me',auth,async(req:AuthRequest,res)=>{const p=z.object({username:z.string().min(3).max(24).optional(),bio:z.string().max(160).optional(),avatarUrl:z.string().url().nullable().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid profile data'});try{res.json(await prisma.user.update({where:{id:req.userId},data:p.data,select:userShape}));}catch{res.status(409).json({error:'Username already in use'});}});
app.get('/rooms',async(req,res)=>{const category=typeof req.query.category==='string'?req.query.category:undefined; const list=await prisma.room.findMany({where:{isActive:true,isPrivate:false,...category?{category}:{}} ,include:{host:{select:{id:true,username:true,avatarUrl:true}},participants:{where:{status:'ACTIVE'},select:{id:true}}},orderBy:{createdAt:'desc'},take:100});res.json(list.map(r=>({...r,participantCount:r.participants.length,participants:undefined})));});
app.post('/rooms',auth,async(req:AuthRequest,res)=>{const p=z.object({name:z.string().min(2).max(80),category:z.string().min(2).max(40),isPrivate:z.boolean().default(false),maxParticipants:z.number().int().min(2).max(1000).default(100)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid room data'});const room=await prisma.room.create({data:{...p.data,hostId:req.userId!,participants:{create:{userId:req.userId!,role:'HOST'}}},include:{host:{select:{id:true,username:true,avatarUrl:true}}});res.status(201).json(room);});
app.get('/rooms/:id',async(req,res)=>{const room=await prisma.room.findUnique({where:{id:req.params.id},include:{host:{select:{id:true,username:true,avatarUrl:true}},participants:{where:{status:'ACTIVE'},include:{user:{select:userShape}}},messages:{orderBy:{createdAt:'desc'},take:50,include:{user:{select:{username:true,avatarUrl:true}}}}});if(!room)return res.status(404).json({error:'Room not found'});res.json(room);});
app.post('/rooms/:id/agora-token',auth,async(req:AuthRequest,res)=>{const appId=process.env.AGORA_APP_ID,certificate=process.env.AGORA_APP_CERTIFICATE;if(!appId||!certificate)return res.status(503).json({error:'Agora is not configured'});const membership=await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId:req.params.id,userId:req.userId!}});if(!membership||membership.status!=='ACTIVE')return res.status(403).json({error:'Join the room first'});const channel=req.params.id;const uid=Number.parseInt(req.userId!.slice(-8),36)%2147483647;const role=membership.role==='LISTENER'?RtcRole.SUBSCRIBER:RtcRole.PUBLISHER;const token=RtcTokenBuilder.buildTokenWithUid(appId,certificate,channel,uid,role,Math.floor(Date.now()/1000)+3600);res.json({appId,channel,token,uid,role:membership.role});});
const io=new Server(httpServer,{cors:{origin:process.env.CLIENT_ORIGIN==='*'?true:process.env.CLIENT_ORIGIN}});io.use((socket,next)=>{try{const raw=socket.handshake.auth?.token;const p=jwt.verify(raw,secret) as {sub:string};socket.data.userId=p.sub;next();}catch{next(new Error('unauthorized'));}});
io.on('connection',socket=>{socket.on('room:join',async({roomId}:{roomId:string},ack)=>{try{const uid=socket.data.userId;const room=await prisma.room.findUnique({where:{id:roomId}});if(!room||!room.isActive)throw Error('Room unavailable');const count=await prisma.roomParticipant.count({where:{roomId,status:'ACTIVE'}});if(count>=room.maxParticipants)throw Error('Room is full');const participant=await prisma.roomParticipant.upsert({where:{roomId_userId:{roomId,userId:uid}},create:{roomId,userId:uid},update:{status:'ACTIVE',leftAt:null}});socket.join(roomId);const key=`room:${roomId}:online`;await redis?.sAdd(key,uid);const state=await prisma.roomParticipant.findMany({where:{roomId,status:'ACTIVE'},include:{user:{select:userShape}}});io.to(roomId).emit('room:participants',state);ack?.({ok:true,participant});}catch(e){ack?.({ok:false,error:e instanceof Error?e.message:'Could not join'});}});socket.on('room:leave',async({roomId}:{roomId:string})=>{await prisma.roomParticipant.updateMany({where:{roomId,userId:socket.data.userId,status:'ACTIVE'},data:{status:'LEFT',leftAt:new Date(),handRaised:false}});await redis?.sRem(`room:${roomId}:online`,socket.data.userId);socket.leave(roomId);io.to(roomId).emit('room:user_left',{userId:socket.data.userId});});socket.on('room:hand',async({roomId,raised}:{roomId:string,raised:boolean})=>{await prisma.roomParticipant.update({where:{roomId_userId:{roomId,userId:socket.data.userId}},data:{handRaised:raised}});io.to(roomId).emit('room:hand',{userId:socket.data.userId,raised});});socket.on('room:chat',async({roomId,body}:{roomId:string,body:string})=>{if(!body?.trim()||body.length>500)return;const msg=await prisma.chatMessage.create({data:{roomId,userId:socket.data.userId,body:body.trim()},include:{user:{select:{username:true,avatarUrl:true}}});io.to(roomId).emit('room:chat',msg);});socket.on('disconnect',()=>undefined);});
app.post('/rooms/:id/participants/:userId/promote',auth,async(req:AuthRequest,res)=>{const host=await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId:req.params.id,userId:req.userId!}}});if(host?.role!=='HOST')return res.status(403).json({error:'Only the host can promote speakers'});const participant=await prisma.roomParticipant.update({where:{roomId_userId:{roomId:req.params.id,userId:req.params.userId}},data:{role:'SPEAKER',handRaised:false}});io.to(req.params.id).emit('room:moderated',{action:'promote',participant});res.json(participant);});
app.post('/rooms/:id/participants/:userId/mute',auth,async(req:AuthRequest,res)=>{const host=await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId:req.params.id,userId:req.userId!}}});if(host?.role!=='HOST')return res.status(403).json({error:'Only the host can mute speakers'});const participant=await prisma.roomParticipant.update({where:{roomId_userId:{roomId:req.params.id,userId:req.params.userId}},data:{isMuted:Boolean(req.body.muted)}});io.to(req.params.id).emit('room:moderated',{action:participant.isMuted?'mute':'unmute',participant});res.json(participant);});
app.delete('/rooms/:id/participants/:userId',auth,async(req:AuthRequest,res)=>{const host=await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId:req.params.id,userId:req.userId!}}});if(host?.role!=='HOST')return res.status(403).json({error:'Only the host can remove users'});const participant=await prisma.roomParticipant.update({where:{roomId_userId:{roomId:req.params.id,userId:req.params.userId}},data:{status:'REMOVED',leftAt:new Date(),handRaised:false}});io.to(req.params.id).emit('room:user_removed',{userId:req.params.userId});res.json(participant);});
io.on('connection', socket => {
  socket.on('room:moderate', async ({roomId, targetUserId, action}, ack) => {
    try {
      const host = await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId,userId:socket.data.userId}}});
      if (host?.role !== 'HOST') throw Error('Only the host can moderate');
      if (targetUserId === socket.data.userId) throw Error('The host cannot moderate themselves');
      const target = await prisma.roomParticipant.findUnique({where:{roomId_userId:{roomId,userId:targetUserId}}});
      if (!target || target.status !== 'ACTIVE') throw Error('Participant is not active');
      const data = action === 'promote' ? {role:RoomRole.SPEAKER,handRaised:false} : action === 'demote' ? {role:RoomRole.LISTENER,isMuted:false} : action === 'mute' ? {isMuted:true} : action === 'unmute' ? {isMuted:false} : {status:'REMOVED',leftAt:new Date(),handRaised:false};
      const participant = await prisma.roomParticipant.update({where:{roomId_userId:{roomId,userId:targetUserId}},data,include:{user:{select:userShape}}});
      io.to(roomId).emit('room:moderated',{action,participant});
      if(action === 'remove') io.to(roomId).emit('room:user_removed',{userId:targetUserId});
      ack?.({ok:true,participant});
    } catch (error) { ack?.({ok:false,error:error instanceof Error ? error.message : 'Moderation failed'}); }
  });
});
app.use((_,res)=>res.status(404).json({error:'Not found'})); httpServer.listen(port,()=>console.log(`MS Rooms API listening on :${port}`));
