import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const rooms = [
  { title: 'Late Night Frequencies', category: 'Music', listeners: 284, host: 'Maya', color: 'coral', avatars: ['M', 'J', 'A'], description: 'soft sounds for the insomniacs & dreamers' },
  { title: 'The Founder’s Table', category: 'Business', listeners: 96, host: 'Eli', color: 'mint', avatars: ['E', 'R', 'S'], description: 'building in public, no pitches required' },
  { title: 'Unfiltered', category: 'Casual Chat', listeners: 62, host: 'Nia', color: 'violet', avatars: ['N', 'T', 'K'], description: 'the group chat, but with strangers' },
  { title: 'Checkpoint', category: 'Gaming', listeners: 41, host: 'Marcus', color: 'blue', avatars: ['M', 'D', 'L'], description: 'what are you playing tonight?' },
];

const speakers = [
  { name: 'Maya Rivers', handle: '@mayarivers', role: 'HOST', initials: 'MR', color: 'coral', active: true },
  { name: 'Jordan Lee', handle: '@jordanlee', role: 'SPEAKER', initials: 'JL', color: 'mint', active: false },
  { name: 'Ari K.', handle: '@arik', role: 'SPEAKER', initials: 'AK', color: 'violet', active: true },
];

function Logo() { return <div className="brand"><span className="brand-mark">⌁</span><span>MS <b>Rooms</b></span></div> }
function Avatar({ initials, color = 'coral', small = false }) { return <div className={`avatar ${color} ${small ? 'small' : ''}`}>{initials}</div> }
function Wave({ compact = false }) { return <div className={`wave ${compact ? 'compact' : ''}`}>{[1,3,5,2,6,4,7,3,5,2,4,1,3].map((n,i)=><i key={i} style={{height: `${n * (compact ? 2 : 3)}px`}} />)}</div> }

function Lobby({ onJoin, onCreate, onProfile }) {
  const [filter, setFilter] = useState('For you');
  return <div className="app-shell">
    <header className="topbar"><Logo /><button className="icon-btn" aria-label="Notifications">♧<span className="notification-dot" /></button></header>
    <main className="content">
      <section className="welcome"><div><p className="eyebrow">WEDNESDAY, 9:41 PM</p><h1>Find your people.</h1><p className="subtle">A room for every mood.</p></div><button className="profile-chip" onClick={onProfile}><Avatar initials="OC" color="violet" small /></button></section>
      <div className="filter-row">{['For you','Trending','Following'].map(item=><button key={item} className={filter === item ? 'filter active' : 'filter'} onClick={()=>setFilter(item)}>{item}</button>)}<button className="search">⌕</button></div>
      <section className="feature-card"><div className="feature-copy"><span className="live-pill"><span /> LIVE NOW</span><h2>Late Night<br/>Frequencies</h2><p>soft sounds for the insomniacs<br/>& dreamers</p><button className="join-feature" onClick={()=>onJoin(rooms[0])}>Join room <span>→</span></button></div><div className="feature-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="art-mic">♩</div><Wave /></div></section>
      <div className="section-heading"><h3>Rooms you might like</h3><button>See all <span>→</span></button></div>
      <div className="room-list">{rooms.slice(1).map(room=><button className="room-card" key={room.title} onClick={()=>onJoin(room)}><div className={`room-art ${room.color}`}><span>{room.category === 'Gaming' ? '⌘' : room.category === 'Business' ? '↗' : '✦'}</span></div><div className="room-info"><div className="room-top"><span className="category">{room.category}</span><span className="listeners">◉ {room.listeners}</span></div><h4>{room.title}</h4><p>{room.description}</p><div className="room-foot"><div className="mini-avatars">{room.avatars.map((a,i)=><Avatar key={i} initials={a} color={['coral','mint','violet'][i]} small />)}</div><span>Hosted by <b>{room.host}</b></span></div></div></button>)}</div>
    </main><nav className="bottom-nav"><button className="nav-item selected"><span>⌂</span>Explore</button><button className="nav-item" onClick={onCreate}><span>＋</span>Create</button><button className="nav-item" onClick={onProfile}><span>◯</span>Profile</button></nav>
  </div>
}

function Room({ room, onBack, onProfile }) {
  const [hand, setHand] = useState(false); const [chat, setChat] = useState(''); const [messages, setMessages] = useState([{name:'Sam', text:'this is exactly what I needed tonight ✨'}, {name:'Maya', text:'welcome in, everyone'}]); const [gift, setGift] = useState(false);
  const send = e => { e.preventDefault(); if(chat.trim()){setMessages([...messages,{name:'You',text:chat}]);setChat('')} };
  return <div className="room-screen"><header className="room-header"><button className="back" onClick={onBack}>←</button><div><span className="live-pill"><span /> LIVE</span><p>{room.category}</p></div><button className="icon-btn">•••</button></header><main className="room-content"><div className="room-title"><h1>{room.title}</h1><p>{room.description}</p><div className="room-meta"><span>◉ {room.listeners + 1} listening</span><span>·</span><span>Public room</span></div></div><div className="people-label"><h3>On stage <span>3</span></h3><button>Invite <span>＋</span></button></div><div className="stage">{speakers.map(person=><div className="person" key={person.name}><div className="person-avatar-wrap"><Avatar initials={person.initials} color={person.color}/>{person.active && <span className="speaking">⌁</span>}</div><strong>{person.name.split(' ')[0]}</strong><span className={`role ${person.role === 'HOST' ? 'host' : ''}`}>{person.role}</span><button className="mute">{person.active ? '♬' : '♩'}</button></div>)}<div className="person"><div className="person-avatar-wrap"><Avatar initials="OC" color="blue"/><span className="hand-icon">{hand ? '✋' : ''}</span></div><strong>You</strong><span className="role">LISTENER</span></div></div><div className="chat-panel"><div className="chat-heading"><h3>Room chat</h3><span>{messages.length + 18} messages</span></div><div className="messages">{messages.map((m,i)=><div className="message" key={i}><Avatar initials={m.name[0]} color={i%2?'mint':'violet'} small/><p><b>{m.name}</b>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={send}><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Say something..."/><button>↑</button></form></div></main><div className="room-actions"><button className={`action-btn ${hand ? 'raised' : ''}`} onClick={()=>setHand(!hand)}><span>{hand ? '✋' : '♧'}</span>{hand ? 'Hand raised' : 'Raise hand'}</button><button className="gift-btn" onClick={()=>setGift(true)}>✦ <span>Send a gift</span></button></div>{gift&&<div className="modal-backdrop" onClick={()=>setGift(false)}><div className="gift-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setGift(false)}>×</button><p className="eyebrow">SEND SOME LOVE</p><h2>Pick a gift for Maya</h2><div className="gifts">{['✦','☀','♥','✺'].map((g,i)=><button key={i} onClick={()=>setGift(false)}><span>{g}</span><small>{[10,25,50,100][i]} coins</small></button>)}</div></div></div>}</div>
}

function Profile({ onBack }) { return <div className="app-shell"><header className="topbar"><button className="back" onClick={onBack}>←</button><Logo /><button className="icon-btn">⚙</button></header><main className="profile-page"><div className="profile-hero"><Avatar initials="OC" color="violet"/><span className="online"/><h1>Olivia Chen</h1><p>@oliviachen</p><p className="bio">curious mind, good conversations.<br/>usually somewhere listening.</p><button className="edit-btn">Edit profile</button></div><div className="stats"><div><b>128</b><span>Following</span></div><div><b>1.2k</b><span>Followers</span></div><div><b>34</b><span>Rooms joined</span></div></div><section className="profile-section"><div className="section-heading"><h3>Privacy & settings</h3></div>{['Account & verification','Who can invite me','Notifications'].map((x,i)=><button className="setting" key={x}><span>{['◉','♧','◌'][i]}</span>{x}<b>›</b></button>)}</section></main><nav className="bottom-nav"><button className="nav-item" onClick={onBack}><span>⌂</span>Explore</button><button className="nav-item"><span>＋</span>Create</button><button className="nav-item selected"><span>◯</span>Profile</button></nav></div> }

function CreateRoom({ onBack, onCreate }) { const [name,setName]=useState(''); return <div className="app-shell"><header className="topbar"><button className="back" onClick={onBack}>←</button><h3>Create a room</h3><span /></header><main className="create-page"><p className="eyebrow">SET THE VIBE</p><h1>What are we talking<br/>about?</h1><label>Room name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sunday morning rituals"/></label><label>Topic category<div className="pills">{['Casual Chat','Music','Gaming','Business'].map((x,i)=><button className={i===0?'chosen':''} key={x}>{x}</button>)}</div></label><div className="toggle-row"><div><b>Make this room private</b><span>Only people with an invite can join</span></div><button className="toggle" /></div><button className="primary wide" onClick={()=>onCreate({title:name||'A fresh conversation',category:'Casual Chat',listeners:0,description:'come as you are'})}>Open room <span>→</span></button></main></div> }

function App(){ const [screen,setScreen]=useState('lobby'); const [room,setRoom]=useState(rooms[0]); return screen==='room'?<Room room={room} onBack={()=>setScreen('lobby')} />:screen==='profile'?<Profile onBack={()=>setScreen('lobby')}/>:screen==='create'?<CreateRoom onBack={()=>setScreen('lobby')} onCreate={r=>{setRoom(r);setScreen('room')}}/>:<Lobby onJoin={r=>{setRoom(r);setScreen('room')}} onCreate={()=>setScreen('create')} onProfile={()=>setScreen('profile')}/> }
createRoot(document.getElementById('root')).render(<App />);
